---
- name: Reload SSH
  become: true
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Restart Docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
