all:
  vars:
    deployment_environment: production
    management_network: 192.168.123.0/24
    management_netmask: 255.255.255.0
    vagrant_management_network: 192.168.124.0/24
    nexus_host_ip: 192.168.123.11
    vm_memory_mb: 4096
  children:
    vms:
      hosts:
        production-vm01:
          ansible_host: 192.168.123.11
          vm_memory_mb: 8192
          vm_cpus: 4
        production-vm02:
          ansible_host: 192.168.123.12
        production-vm03:
          ansible_host: 192.168.123.13
        production-vm04:
          ansible_host: 192.168.123.14
        production-vm05:
          ansible_host: 192.168.123.15
        production-vm06:
          ansible_host: 192.168.123.16
    nexus_machine:
      hosts:
        production-vm01: {}
    k8s_control_plane:
      children:
        k8s_bootstrap_control_plane:
          hosts:
            production-vm04: {}
        k8s_additional_control_planes:
          hosts:
            production-vm05: {}
            production-vm06: {}
    k8s_workers:
      hosts:
        production-vm01: {}
        production-vm02: {}
        production-vm03: {}
